name: DAST Scan

on:
  workflow_dispatch:

jobs:
  run-zap:
    runs-on: ubuntu-latest
    steps:
      - name: Создать рабочую директорию
        run: mkdir -p zap

      - name: Проверка доступности цели
        run: |
          for i in {1..10}; do
            if curl -s --head http://185.178.44.115:8080 | grep "200 OK" > /dev/null; then
              echo "✅ Сайт доступен!"
              break
            else
              echo "⏳ Ждём доступности сайта..."
              sleep 10
            fi
          done

      - name: Run OWASP ZAP Full Scan
        run: |
          docker run --rm \
            -u root \
            -v $(pwd)/zap:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t http://185.178.44.115:8080 \
            -r zap-report.html \
            -x zap-report.xml

      - name: Upload ZAP Report to DefectDojo
        env:
          DD_TOKEN: ${{ secrets.DD_TOKEN }}
        run: |
          curl -v -X POST http://185.178.44.115:8080/api/v2/import-scan/ \
            -H "Authorization: Token $DD_TOKEN" \
            -F "file=@zap/zap-report.xml" \
            -F "scan_type=ZAP Scan" \
            -F "engagement=1" \
            -F "minimum_severity=Low" \
            -F "active=true" \
            -F "verified=true"
