name: DAST Scan

on:
  workflow_dispatch:

jobs:
  run-zap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Создание директории для отчётов
        run: mkdir -p zap

      - name: Запуск OWASP ZAP Full Scan
        run: |
          docker run --rm -u root \
            -v $(pwd)/zap:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t http://185.178.44.115:8080 \
            -r zap-report.html \
            -x zap-report.xml

      - name: Проверка наличия отчёта ZAP
        run: |
          echo "📁 Содержимое директории zap:"
          ls -lah zap
          if [ ! -f zap/zap-report.xml ]; then
            echo "❌ ZAP отчёт не найден. Остановка."
            exit 1
          fi
          echo "✅ ZAP отчёт найден."

      - name: Загрузка отчёта в DefectDojo
        env:
          DD_TOKEN: ${{ secrets.DD_TOKEN }}
        run: |
          echo "📤 Отправка отчёта в DefectDojo..."
          RESPONSE=$(curl -s -w "%{http_code}" -o response.txt -X POST http://185.178.44.115:8080/api/v2/import-scan/ \
            -H "Authorization: Token $DD_TOKEN" \
            -F "file=@zap/zap-report.xml" \
            -F "scan_type=ZAP Scan" \
            -F "engagement=1" \
            -F "minimum_severity=Low" \
            -F "active=true" \
            -F "verified=true")

          if [ "$RESPONSE" -eq "201" ]; then
            echo "✅ Отчёт успешно загружен в DefectDojo"
          else
            echo "❌ Ошибка загрузки отчёта. HTTP статус: $RESPONSE"
            echo "--- Ответ сервера:"
            cat response.txt
            exit 1
          fi
