name: DAST Scan

on:
  workflow_dispatch:

jobs:
  run-zap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run OWASP ZAP Full Scan
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t http://185.178.44.115:8080 \
            -r zap-report.html \
            -x zap-report.xml || true
        # Пояснение: || true гарантирует, что workflow не упадёт при exit code 3 (если найдены уязвимости)

      - name: Upload ZAP Report to DefectDojo
        env:
          DD_TOKEN: ${{ secrets.DD_TOKEN }}
        run: |
          echo "Uploading scan result to DefectDojo..."
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://185.178.44.115:8080/api/v2/import-scan/ \
            -H "Authorization: Token $DD_TOKEN" \
            -F "file=@zap-report.xml" \
            -F "scan_type=ZAP Scan" \
            -F "engagement=1" \
            -F "minimum_severity=Low" \
            -F "active=true" \
            -F "verified=true")

          if [ "$RESPONSE" -eq "201" ]; then
            echo "✅ Report uploaded successfully"
          else
            echo "❌ Failed to upload report to DefectDojo. HTTP Status: $RESPONSE"
            exit 1
          fi

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap-report.html
            zap-report.xml
