name: DAST Scan

on:
  workflow_dispatch:

jobs:
  run-zap:
    runs-on: ubuntu-latest
    steps:
      - name: Run OWASP ZAP
        run: |
          docker run --rm -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t http://your-vps:8080 \
            -r zap-report.html \
            -x zap-report.xml

      - name: Upload ZAP Report to DefectDojo
        env:
          DD_TOKEN: ${{ secrets.DD_TOKEN }}
        run: |
          curl -X POST http://185.178.44.115/:8080/api/v2/import-scan/ \
            -H "Authorization: Token $DD_TOKEN" \
            -F "file=@zap-report.xml" \
            -F "scan_type=ZAP Scan" \
            -F "engagement=1" \
            -F "minimum_severity=Low" \
            -F "active=true" \
            -F "verified=true"
